use educayso_facae;
drop view etapamovilidadalumno1;
create view etapamovilidadalumno1 as select etapamovilidadalumno.idetapamovilidadalumno,etapamovilidadalumno.idmovilidadalumno, etapamovilidad.idetapamovilidad, etapamovilidad.nombre as etapa,etapamovilidadalumno.fecha fecha   from etapamovilidadalumno,movilidadalumno,etapamovilidad  where etapamovilidadalumno.idmovilidadalumno=movilidadalumno.idmovilidadalumno  and etapamovilidadalumno.idetapamovilidad=etapamovilidad.idetapamovilidad;
