
use educayso_facae;
drop view fechacalendario1;
create view fechacalendario1 as select fechacalendario.idfechacalendario,fechacalendario.fechacalendario,fechacalendario.actividad,fechacalendario.hito ,periodoacademico.idperiodoacademico,periodoacademico.nombrecorto as elperiodoacademico,departamento.iddepartamento from fechacalendario,calendarioacademico, periodoacademico,departamento where fechacalendario.idcalendarioacademico=calendarioacademico.idcalendarioacademico and calendarioacademico.idperiodoacademico=periodoacademico.idperiodoacademico and calendarioacademico.iddepartamento=departamento.iddepartamento ;
