use educayso_facae;
drop table miembrocomisionacademica;
create view  miembrocomisionacademica1 as miembrocomisionacademica.*, comisionacademica.nombre as lacomisionacademica,periodoacademica.nombrecorto as elperiodoacademico  from miembrocomisionacademica,periodoacademico,comisionacademica where miembrocomisionacademica.idperiodoacademico=periodoacademico.idperiodoacademico and miembrocomisionacademica.idcomisionacademica=comisionacademica.idcomisionacademica;



